### ISSUE TITLE
Detect when -lz doesn't work and compile zlib from source

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/libz-sys#20]
We've got all the sources on hand! We should [detect this failure mode](https://github.com/alexcrichton/libz-sys/blob/812e0c238778fb1a9f93e5c43b9b0c17a018a789/build.rs#L52-L53) and defer to `build_zlib()`

**Comment by alexcrichton** [comment]
@evhub if you're willing to write up a patch for this I'd love to review!

**Comment by cssivision** [comment]
i think i can fire a pr to fix this(for learning rust).

**Comment by alexcrichton** [comment]
Awesome, thanks! Let me know if you have any questions

**Comment by cssivision** [comment]
it seems that i have made a mistake, i try to detect `libz.so` using crate `pkg-config` with:
```rust
// try this
pkg_config::find_library("zlib").is_ok() 
// alse this
pkg_config::find_library("z").is_ok()
```
without installing `zlib-dev` they both return `false`, after install `zlib-dev` also return `false`.
it seems `pkg-config` is not work for this lib, finally i found the dynamic lib in path `/lib/x86_64-linux-gnu/libz.so.1`,  zlib1g-dev package in ubuntu 14.04 does not contain pkg-config file zlib.pc.

i will dive into crate `pkg-config`,try to found the solution, @alexcrichton any suggestions?

**Comment by cssivision** [comment]
it has nothing to do with `pkg-config`. it's a exception in ubuntu 14.04, there is no default `libz.so` installed,  in centos 7 there exists `libz.so`, without `zlib-devel` installed, also can build this crate, but `pkg_config::find_library("zlib").is_ok()` will return `false`, after installing `zlib-devel`, `pkg_config::find_library("zlib").is_ok()` will return `true`. 

but ubuntu 14.04 will always return `false`, because zlib1g-dev package in ubuntu 14.04 does not contain pkg-config file zlib.pc, build from source may fix this. in other linux distro there exists `libz.so`, but without `zlib-devel` will also build from source code which is not necessary.

**Comment by alexcrichton** [comment]
Ah yeah the reason there's a fallback of just printing `rustc-link-lib=z` is because it seemed common at the time to find `libz.so` *without* having pkg-config installed. I think what we may want to do is to just try compilling a simple C file with `-lz` and see if it compiles and links correctly. If that fails we'd fall back to `build_zlib()`

**Comment by cssivision** [comment]
like this?
```rust
let out = env::var("OUT_DIR").unwrap();
let p = Path::new(&out).join("foo.c");
let mut f = File::open(&p).unwrap();
f.write_all(b"#include <zlib.h>\nint foo()\n{\n    return 0;\n}").unwrap();
gcc::Config::new()
    .file(Path::new(&out).join("foo.c"))
    .flag("-lz")
    .try_compile("libfoo.a");
```

**Comment by alexcrichton** [comment]
Ah unfortunately that won't actually invoke the linker, so it won't detect the failure. I think it's fine though to use `gcc`'s `get_compiler` method and then use that to invoke the compiler manually?

**Comment by cssivision** [comment]
yes, use `get_compiler().to_command().exec()` does the trick. but i finally find that `pkg_config::probe_linrary("zlib").is_ok()` works for ubuntu 14.04. it turns out that there is something wrong with the my server. built from a new ubuntu 14.04 server, everything is just ok. 

find libz.so without having pkg-config installed is nice, but in the `build.rs` we have imported crate `pkg_config`,  i prefer using `pkg_config`. @alexcrichton which one do you prefer?  using `get_compiler` will have to wait `gcc-rs` release version which contains [`try_get_compiler`](https://github.com/alexcrichton/gcc-rs/blob/master/src/lib.rs#L907) function, or `get_compiler` may be panic.

**Comment by alexcrichton** [comment]
Ah sorry for the delay! @cssivision I think we [already use `pkg_config`](https://github.com/alexcrichton/libz-sys/blob/c1814bbe601e4abcd92ada6285336156facdd28f/build.rs#L32), right? Is there a different invocation you're thinking of?

**Comment by BusyJay** [comment]
Why not just compiling from sources and link to system library when required? So we can get a consistent binary (always link to the same version of zlib) by default no matter whether zlib is installed on host or not.
